export const gyms = [
  {
    id: 'martina-beku',
    slug: 'martina-beku',
    name: 'Martina Beku',
    fullName: 'Cvič Sám – Martina Beku',
    address: 'Martina Benku 7887/1A, 080 01 Prešov',
    tag: 'Hlavná prevádzka',
    hours: '24/7 cez aplikáciu',
    bookingUrl: 'https://gymify.sk/gyms/cvic-sam/booking',
    mapsUrl: 'https://maps.google.com/?q=Martina+Benku+7887/1A+Presov',
    color: '#4A9EFF',
    bgImage: 'https://cvicsam.sk/wp-content/uploads/2025/11/foto_fitko-002-scaled.jpg',
    heroImage: 'https://cvicsam.sk/wp-content/uploads/2025/11/foto_fitko-008-scaled.jpg',
    description: 'Hlavná prevádzka Cvič Sám v Prešove. Moderné vybavenie, súkromný priestor a pohodlie priamo v centre mesta. Rezervujete si termín cez aplikáciu Gymify a celý priestor máte len pre seba.',
    features: ['Moderné stroje a voľné váhy', 'Súkromná šatňa', 'Klimatizácia', 'Kávovar', 'Bezbariérový prístup'],
  },
  {
    id: 'svaby',
    slug: 'svaby',
    name: 'Šváby',
    fullName: 'Cvič Sám – Šváby',
    address: 'Švábska 41/A, 080 05 Prešov',
    tag: 'Druhá prevádzka',
    hours: '24/7 cez aplikáciu',
    bookingUrl: 'https://gymify.sk/gyms/cvic-sam-svaby/booking?reservable=238',
    mapsUrl: 'https://maps.google.com/?q=Svabska+41/A+Presov',
    color: '#00D1FF',
    bgImage: 'https://cvicsam.sk/wp-content/uploads/2025/11/foto_fitko-004-scaled.jpg',
    heroImage: 'https://cvicsam.sk/wp-content/uploads/2025/11/foto_fitko-011-scaled.jpg',
    description: 'Druhá prevádzka Cvič Sám v prešovskej štvrti Šváby. Rovnaká kvalita vybavenia a súkromia ako hlavná prevádzka. Ideálna voľba pre obyvateľov južného Prešova.',
    features: ['Plne vybavená posilňovňa', 'Súkromný vstup cez QR kód', 'Parkovanie pred prevádzkou', 'Klimatizácia', 'Kávovar'],
  },
  {
    id: 'hronska-ke',
    slug: 'hronska-ke',
    name: 'Hronská KE',
    fullName: 'Cvič Sám – Hronská KE',
    address: 'Hronská, Košice',
    tag: 'Košice',
    hours: '24/7 cez aplikáciu',
    bookingUrl: 'https://gymify.sk/gyms/cvic-sam/booking',
    mapsUrl: 'https://maps.google.com/?q=Hronska+Kosice',
    color: '#4A9EFF',
    bgImage: 'https://cvicsam.sk/wp-content/uploads/2025/11/foto_fitko-007-scaled.jpg',
    heroImage: 'https://cvicsam.sk/wp-content/uploads/2025/11/foto_fitko-012-scaled.jpg',
    description: 'Najnovšia prevádzka Cvič Sám v Košiciach. Súkromná posilňovňa s rovnakým konceptom – rezervujte si čas, otvorte dvere QR kódom a cvičte v úplnom súkromí.',
    features: ['Kompletné vybavenie pre silový tréning', 'Súkromná šatňa', 'Klimatizácia', 'Parkovanie v okolí', 'Prístup 24/7'],
  },
];